// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn']
    CheckDialog: typeof import('./components/check-dialog/index.vue')['default']
    Dialog: typeof import('./components/dialog/index.vue')['default']
    Floor: typeof import('./components/floor/index.vue')['default']
    Header: typeof import('./components/Header/index.vue')['default']
    Input: typeof import('./components/Input/index.vue')['default']
    NumLack: typeof import('./components/NumLack/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SDialog: typeof import('./components/s-dialog/index.vue')['default']
    Slide: typeof import('./components/slide/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    Wxapp: typeof import('./components/wxapp/index.vue')['default']
    WxappLogin: typeof import('./components/wxapp-login/index.vue')['default']
  }
}

export {}
